version: '0.1'

services:
  webapp:
    platform: linux/arm64
    build: .
    image: minecopre/webapp
    ports:
      - 8081:8081
    volumes:
      - /src/main/resources/:/webapp/resources
      - /contas/:/webapp/contas
      - /tmpFiles/:/webapp/tmpFiles