services:
   webapp:
    container_name: photusRetratusWebapp
    platform: linux/amd64
    build: .
    image: webapp
    logging:
      driver: journald
    ports:
      - 8081:8081
    volumes:
      - /var/www/photuseretratus/webapp/resources:/webapp/resources
    restart: unless-stopped
